# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd46201d33404085660ee9171d1dbe78fc60130b1a0275e66ecf130c84b7c4047653c9ed756f204c7b7d8962dc51b39075a3f3afd798785f37fcdf62f29a649

test:
  secret_key_base: cf6b2b5b8ffd1e18860405913c6a88463c0f53303bc23c76c13a5ff086a5c8d0e4953549e531855d502f3b79034b3e2bad7bcf3d44ab2b2898cbaa9d8f47a19b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
